selected_scheme scheme-basic
collection-basic 1
collection-bibtexextra 0
collection-fontsextra 0
collection-fontsrecommended 0
collection-langchinese 0
collection-latex 1
collection-latexextra 0
collection-latexrecommended 0
collection-mathscience 0
collection-xetex 1
tlpdbopt_autobackup 0
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0