os: linux
dist: bionic
language: java
install:
  # debian-supplied pandoc is very old --> install manually
  - pandoc_deb="pandoc-2.9.1-1-amd64.deb"
  - wget "https://github.com/jgm/pandoc/releases/download/2.9.1/${pandoc_deb}"
  - sudo dpkg -i ${pandoc_deb}
  - rm ${pandoc_deb}

  # texlife
  - PROJECTDIR=$(pwd)
  - cd /tmp && wget mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xvzf install-tl-unx.tar.gz
  - cd install-tl-*
  - chmod +x install-tl
  - sudo ./install-tl --profile=$PROJECTDIR/texlive.profile
  - PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH
  - pdflatex -v
  - cd $PROJECTDIR

  # Initialization and packages for tlmgr
  - sudo apt-get install xzdec
  - tlmgr init-usertree
  - sh update-tlmgr-latest.sh

  # for rendering the PDFs
  - sudo apt-get install poppler-utils

  # for executing python based pandoc filters
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade setuptools

  # install python filters
  - pip3 install pandoc-latex-environment

  # packages needed for the template
  - tlmgr install xecjk filehook unicode-math ucharcat pagecolor babel-german ly1 mweights sourcecodepro sourcesanspro mdframed needspace fvextra footmisc footnotebackref background

  # packages only needed for some examples (that include packages via header-includes)
  - tlmgr install awesomebox fontawesome5
before_script:
  - cd examples
script:
  - sh build-examples.sh